name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install AWS CLI
      run: pip install awscli

    - name: Zip application
      run: zip -r app.zip . -x '*.git*'

    - name: Deploy to Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
      run: |
        aws elasticbeanstalk create-application-version --application-name <your-app-name> --version-label $GITHUB_SHA --source-bundle S3Bucket=<your-bucket>,S3Key=app.zip
        aws elasticbeanstalk update-environment --environment-name <your-env-name> --version-label $GITHUB_SHA
